import javax.swing.JOptionPane;

/**
 * Add/Edit Snippet popup window (paired with SnippetFormDialog.form,
 * editable in the NetBeans GUI Builder / Design tab).
 *
 * Opened from VaultGUI as a modal dialog: passing null means "add a new
 * snippet"; passing an existing Snippet means "edit this one".
 */
public class SnippetFormDialog extends javax.swing.JDialog {

    private final DatabaseHelper dbHelper = new DatabaseHelper();
    private int editingId = -1;
    private boolean savedSuccessfully = false;

    /**
     * Creates new form SnippetFormDialog
     */
    public SnippetFormDialog(java.awt.Frame parent, Snippet existingSnippet) {
        super(parent, true);
        initComponents();
        setLocationRelativeTo(parent);

        if (existingSnippet == null) {
            editingId = -1;
            lblFormTitle.setText("Add New Snippet");
            cmbLanguage.setSelectedItem(PreferencesHelper.getLastLanguage());
        } else {
            editingId = existingSnippet.getId();
            lblFormTitle.setText("Edit Snippet");
            cmbLanguage.setSelectedItem(existingSnippet.getLanguage());
            txtTitle.setText(existingSnippet.getTitle());
            txtCode.setText(existingSnippet.getCode());
        }
    }

    /** True if the user successfully saved a snippet before closing this dialog. */
    public boolean wasSaved() {
        return savedSuccessfully;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFormTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbLanguage = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCode = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Snippet");
        setBackground(new java.awt.Color(245, 245, 245));

        lblFormTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblFormTitle.setText("Add New Snippet");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Language:");

        cmbLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Java", "SQL", "HTML", "Python", "PHP" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Snippet Title:");

        txtTitle.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Code:");

        txtCode.setColumns(20);
        txtCode.setFont(new java.awt.Font("Consolas", 0, 13)); // NOI18N
        txtCode.setRows(5);
        jScrollPane1.setViewportView(txtCode);

        btnSave.setBackground(new java.awt.Color(21, 101, 192));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.setBorderPainted(false);
        btnSave.addActionListener(this::btnSaveActionPerformed);

        btnCancel.setBackground(new java.awt.Color(0, 137, 123));
        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel");
        btnCancel.setBorderPainted(false);
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFormTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addGap(20, 20, 20)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblFormTitle)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String title = txtTitle.getText().trim();
        String code = txtCode.getText().trim();
        String language = (String) cmbLanguage.getSelectedItem();

        if (title.isEmpty() || code.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both a title and code.");
            return;
        }

        boolean success = (editingId == -1)
                ? dbHelper.insertSnippet(title, language, code)
                : dbHelper.updateSnippet(editingId, title, language, code);

        if (success) {
            PreferencesHelper.saveLastLanguage(language);
            savedSuccessfully = true;
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error saving snippet. Please try again.");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbLanguage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFormTitle;
    private javax.swing.JTextArea txtCode;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
