import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;

/**
 * Code Snippet Vault - main window (paired with VaultGUI.form, editable in
 * the NetBeans GUI Builder / Design tab).
 *
 * Navigation: clicking "Add New Snippet" or "Edit Selected" opens
 * SnippetFormDialog as a modal popup window; closing it returns here.
 */
public class VaultGUI extends javax.swing.JFrame {

    private final DatabaseHelper dbHelper = new DatabaseHelper();
    private List<Snippet> currentSnippets;
    private JPanel emptyStatePanel;
    private JLabel emptyStateLabel;

    /**
     * Creates new form VaultGUI
     */
    public VaultGUI() {
        initComponents();

        snippetTable.setModel(new SnippetTableModel(new Object[]{"Title", "Language", "Date Created"}));
        snippetTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        setLocationRelativeTo(null);
        setIconImage(createAppIcon());

        emptyStateLabel = new JLabel("", SwingConstants.CENTER);
        emptyStateLabel.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        emptyStateLabel.setForeground(Color.GRAY);
        emptyStatePanel = new JPanel(new BorderLayout());
        emptyStatePanel.setBackground(Color.WHITE);
        emptyStatePanel.add(emptyStateLabel, BorderLayout.CENTER);

        txtSearch.getDocument().addDocumentListener(new SearchDocumentListener(this::loadSnippets));

        // Setting the combo box's selected item can fire its actionPerformed
        // handler immediately, which calls loadSnippets() - so this must come
        // after emptyStateLabel/emptyStatePanel above are already built.
        cmbFilterLanguage.setSelectedItem(PreferencesHelper.getLastFilter());

        loadSnippets();
    }

    /**
     * Draws a small branded icon in code (a blue rounded square with a
     * "&lt;/&gt;" code mark) so the app has a window icon without needing an
     * external image file bundled with the project.
     */
    private java.awt.Image createAppIcon() {
        int size = 64;
        BufferedImage icon = new BufferedImage(size, size, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = icon.createGraphics();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        g2.setColor(new Color(21, 101, 192));
        g2.fillRoundRect(2, 2, size - 4, size - 4, 16, 16);

        g2.setColor(Color.WHITE);
        g2.setFont(new Font("Consolas", Font.BOLD, 24));
        FontMetrics fm = g2.getFontMetrics();
        String text = "</>";
        int textX = (size - fm.stringWidth(text)) / 2;
        int textY = (size - fm.getHeight()) / 2 + fm.getAscent();
        g2.drawString(text, textX, textY);

        g2.dispose();
        return icon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelFilter = new javax.swing.JLabel();
        cmbFilterLanguage = new javax.swing.JComboBox<>();
        jLabelSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        btnGoAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        snippetTable = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnTip = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Code Snippet Vault");
        setBackground(new java.awt.Color(245, 245, 245));
        setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabelTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelTitle.setText("Code Snippet Vault");

        jLabelFilter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelFilter.setText("Filter by language:");

        cmbFilterLanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Java", "SQL", "HTML", "Python", "PHP" }));
        cmbFilterLanguage.addActionListener(this::cmbFilterLanguageActionPerformed);

        jLabelSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelSearch.setText("Search:");

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        btnRefresh.setBackground(new java.awt.Color(0, 137, 123));
        btnRefresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.setBorderPainted(false);
        btnRefresh.addActionListener(this::btnRefreshActionPerformed);

        btnGoAdd.setBackground(new java.awt.Color(21, 101, 192));
        btnGoAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGoAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnGoAdd.setText("Add New Snippet");
        btnGoAdd.setBorderPainted(false);
        btnGoAdd.addActionListener(this::btnGoAddActionPerformed);

        jScrollPane1.setViewportView(snippetTable);

        btnEdit.setBackground(new java.awt.Color(21, 101, 192));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit Selected");
        btnEdit.setBorderPainted(false);
        btnEdit.addActionListener(this::btnEditActionPerformed);

        btnDelete.setBackground(new java.awt.Color(229, 57, 53));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete Selected");
        btnDelete.setBorderPainted(false);
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnTip.setBackground(new java.awt.Color(239, 108, 0));
        btnTip.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTip.setForeground(new java.awt.Color(255, 255, 255));
        btnTip.setText("Get Coding Tip");
        btnTip.setBorderPainted(false);
        btnTip.addActionListener(this::btnTipActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFilter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFilterLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabelSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGoAdd))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTip)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelTitle)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFilter)
                    .addComponent(cmbFilterLanguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh)
                    .addComponent(btnGoAdd))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)
                    .addComponent(btnTip))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbFilterLanguageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFilterLanguageActionPerformed
        PreferencesHelper.saveLastFilter((String) cmbFilterLanguage.getSelectedItem());
        loadSnippets();
    }//GEN-LAST:event_cmbFilterLanguageActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadSnippets();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnGoAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoAddActionPerformed
        SnippetFormDialog dialog = new SnippetFormDialog(this, null);
        dialog.setVisible(true);
        if (dialog.wasSaved()) {
            loadSnippets();
        }
    }//GEN-LAST:event_btnGoAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int row = snippetTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a snippet to edit.");
            return;
        }
        Snippet selected = currentSnippets.get(row);
        SnippetFormDialog dialog = new SnippetFormDialog(this, selected);
        dialog.setVisible(true);
        if (dialog.wasSaved()) {
            loadSnippets();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = snippetTable.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a snippet to delete.");
            return;
        }
        Snippet selected = currentSnippets.get(row);
        int confirm = JOptionPane.showConfirmDialog(this,
                "Delete \"" + selected.getTitle() + "\"?", "Confirm Delete", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            dbHelper.deleteSnippet(selected.getId());
            loadSnippets();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnTipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipActionPerformed
        btnTip.setEnabled(false);
        btnTip.setText("Loading...");
        new CodingTipWorker(btnTip, this).execute();
    }//GEN-LAST:event_btnTipActionPerformed

    private void loadSnippets() {
        String filter = (String) cmbFilterLanguage.getSelectedItem();
        String searchText = txtSearch.getText().trim().toLowerCase();

        if (filter == null || filter.equals("All")) {
            currentSnippets = dbHelper.getAllSnippets();
        } else {
            currentSnippets = dbHelper.getSnippetsByLanguage(filter);
        }

        if (!searchText.isEmpty()) {
            List<Snippet> matches = new ArrayList<>();
            for (Snippet s : currentSnippets) {
                if (s.getTitle().toLowerCase().contains(searchText)) {
                    matches.add(s);
                }
            }
            currentSnippets = matches;
        }

        SnippetTableModel model = (SnippetTableModel) snippetTable.getModel();
        model.setRowCount(0);
        for (Snippet s : currentSnippets) {
            model.addRow(new Object[]{s.getTitle(), s.getLanguage(), s.getDateCreated()});
        }

        if (currentSnippets.isEmpty()) {
            boolean noFilterActive = searchText.isEmpty() && (filter == null || filter.equals("All"));
            emptyStateLabel.setText(noFilterActive
                    ? "No snippets yet \u2014 click \"Add New Snippet\" to get started."
                    : "No snippets match your search or filter.");
            jScrollPane1.setViewportView(emptyStatePanel);
        } else {
            jScrollPane1.setViewportView(snippetTable);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VaultGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new VaultGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnGoAdd;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTip;
    private javax.swing.JComboBox<String> cmbFilterLanguage;
    private javax.swing.JLabel jLabelFilter;
    private javax.swing.JLabel jLabelSearch;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable snippetTable;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
